// GENERATED by scripts/render-3d-sprites.mjs v2 — do not edit by hand.
// Boss sprite: image aspect, alpha bbox of the body (fractions), and the roof
// light panel rectangle (fractions of the image) where Car3D draws the sequence.
export const BOSS_SPRITE_GEOMETRY = {
  "aspect": 0.531,
  "w": 0.944,
  "h": 0.847,
  "cx": 0,
  "panel": {
    "cx": 0.5,
    "cy": 0.289,
    "w": 0.588,
    "h": 0.329
  }
};
