// GENERATED by scripts/render-3d-sprites.mjs — do not edit by hand.
// Per vehicle type, measured from the baked sprite: image aspect (W/H) and the
// alpha bbox of the solid body + outline as fractions of the image (cx = body
// centre offset, + = right). The soft baked shadow is excluded.
export const CAR_SPRITE_GEOMETRY = {
  "small": {
    "aspect": 0.482,
    "w": 0.862,
    "h": 0.638,
    "cx": 0
  },
  "big": {
    "aspect": 0.693,
    "w": 0.926,
    "h": 0.781,
    "cx": 0
  },
  "jeep": {
    "aspect": 0.642,
    "w": 0.926,
    "h": 0.844,
    "cx": 0
  },
  "truck": {
    "aspect": 0.554,
    "w": 0.926,
    "h": 0.807,
    "cx": 0
  },
  "bigrig": {
    "aspect": 0.497,
    "w": 0.925,
    "h": 0.879,
    "cx": 0
  },
  "tank": {
    "aspect": 0.682,
    "w": 0.934,
    "h": 0.735,
    "cx": 0
  }
};
