// GENERATED by scripts/render-3d-sprites.mjs — do not edit by hand.
// Per vehicle type, measured from the baked sprite: image aspect (W/H) and the
// alpha bbox of the solid body + outline as fractions of the image (cx = body
// centre offset, + = right). The soft baked shadow is excluded.
export const CAR_SPRITE_GEOMETRY = {
  "small": {
    "aspect": 0.461,
    "w": 0.874,
    "h": 0.687,
    "cx": 0
  },
  "big": {
    "aspect": 0.695,
    "w": 0.941,
    "h": 0.814,
    "cx": 0
  },
  "jeep": {
    "aspect": 0.635,
    "w": 0.941,
    "h": 0.868,
    "cx": 0
  },
  "truck": {
    "aspect": 0.556,
    "w": 0.943,
    "h": 0.837,
    "cx": 0
  },
  "bigrig": {
    "aspect": 0.495,
    "w": 0.943,
    "h": 0.846,
    "cx": 0
  },
  "tank": {
    "aspect": 0.647,
    "w": 0.951,
    "h": 0.699,
    "cx": 0
  }
};
