// Level auto-tuner — finds the `heft` (spawn-mix weight, 0 = lightest car types,
// 1 = heaviest; see CarTypes.heftWeights) that puts each level at the centre of
// its win-rate band (tools/balance-sim.js bands, skill=average), and when even
// the lightest mix is too hard, the goal scale that fixes it. Car HP per TYPE is
// fixed on every level — only the mix moves.
//
//   node tools/tune-levels.mjs 4-40 [runs=200]   → JSON { id: { hp, goalScale, win } }
//
// It only RECOMMENDS; LevelManager.js stays the hand-edited source of truth.
import { LevelManager, LEVEL_COUNT } from '../src/game/LevelManager.js';
import { bandFor } from './bands.mjs';
import { SimulationRunner } from '../src/simulation/SimulationRunner.js';

const [range = `4-${LEVEL_COUNT}`, runsArg = '200'] = process.argv.slice(2).filter(a => !a.startsWith('--'));
const [lo, hi = lo] = range.split('-').map(Number);
const RUNS = Number(runsArg);
const band = (id) => { const b = bandFor(id); return [b.lo, b.hi]; };

// A level's authored trait mix, before any tuning scale was applied (late levels
// carry it as baseTraits; the hand-tuned L1-40 just use traits).
const baseTraitsOf = (cfg) => cfg.baseTraits ?? cfg.traits ?? null;
const scaleTraits = (t, k) => t && Object.fromEntries(Object.entries(t).map(([n, p]) => [n, +(p * k).toFixed(4)]));

// Boss goals and 'kill N of trait X' goals are the level's identity — never scaled.
const scalable = (g) => g.type !== 'defeatBoss' && g.type !== 'destroyTrait';

function winRate(cfg, heft, traitScale = 1, goalScale = 1) {
  const traits = scaleTraits(baseTraitsOf(cfg), traitScale);
  const c = { ...cfg, worldConfig: { ...cfg.worldConfig, heft }, ...(traits ? { traits } : {}),
    goals: (cfg.baseGoals ?? cfg.goals).map(g => ({ ...g, count: scalable(g) ? Math.max(1, Math.round(g.count * goalScale)) : g.count })) };
  const r = SimulationRunner.fromLevel(c, { skill: 'average' });
  let w = 0;
  for (let s = 1; s <= RUNS; s++) if (r.runLevel(s).won) w++;
  return (w / RUNS) * 100;
}

// The authored idea (trait mix, goals) is what makes a level itself, so the tuner
// spends its freedom in this order: heft inside a sane window first, then ease the
// trait mix, and only then shrink goals. A level that needs goals x0.7 or trait
// scale < 0.4 to be winnable is flagged — that is a design problem, not tuning.
const HEFT_LO = 0.2, HEFT_HI = 1;
const TRAIT_STEPS = [1, 0.85, 0.7, 0.55, 0.4];
const GOAL_STEPS = [1, 0.9, 0.8, 0.7];

const out = {};
for (let id = lo; id <= hi; id++) {
  const lm = new LevelManager(); lm.goToLevel(id); const cfg = lm.current;
  const [bLo, bHi] = band(id); const target = (bLo + bHi) / 2;
  let ts = 1, gs = 1;
  const traitGoal = (cfg.baseGoals ?? cfg.goals).some(g => g.type === 'destroyTrait');
  const heftLo = traitGoal ? 0 : HEFT_LO;                 // a trait goal needs the trait supply intact
  const traitSteps = traitGoal ? [1] : TRAIT_STEPS;
  const goalSteps = (cfg.baseGoals ?? cfg.goals).some(scalable) ? GOAL_STEPS : [1];
  search: for (const g of goalSteps) for (const t of traitSteps) {
    // Ordered so goals only move once the trait mix is already at its floor.
    if (g !== 1 && t !== traitSteps[traitSteps.length - 1]) continue;
    ts = t; gs = g;
    if (winRate(cfg, heftLo, t, g) >= target) break search;
  }
  let a = heftLo, b = HEFT_HI;
  for (let i = 0; i < 8; i++) {
    const m = (a + b) / 2;
    if (winRate(cfg, m, ts, gs) > target) a = m; else b = m;
  }
  const heft = Math.round(((a + b) / 2) * 100) / 100;
  const win = winRate(cfg, heft, ts, gs);
  out[id] = { heft, ts, gs, win: +win.toFixed(1), band: `${bLo}-${bHi}` };
  const flag = (ts < 0.55 || gs < 1 || win < bLo || win > bHi) ? '  <-- CHECK' : '';
  console.error(`L${id}: heft ${heft} traits x${ts} goals x${gs} -> ${win.toFixed(1)}% (${bLo}-${bHi})${flag}`);
}
console.log(JSON.stringify(out));
if (process.argv.includes('--write')) {
  const { LATE_TUNING } = await import('../src/game/lateTuning.js');
  const merged = { ...LATE_TUNING };
  for (const [id, r] of Object.entries(out)) if (Number(id) > 40) merged[id] = { heft: r.heft, ts: r.ts, gs: r.gs };
  const body = Object.entries(merged).sort((a, b) => a[0] - b[0]).map(([id, r]) => `  ${id}: { heft: ${r.heft}, ts: ${r.ts}, gs: ${r.gs} },`).join('\n');
  const { writeFileSync } = await import('node:fs');
  writeFileSync(new URL('../src/game/lateTuning.js', import.meta.url),
    `// GENERATED by \`node tools/tune-levels.mjs 41-100 --write\`. Do not hand-edit.\n// heft = spawn-mix weight, ts = trait-mix scale, gs = goal scale (1 = authored).\nexport const LATE_TUNING = {\n${body}\n};\n`);
  console.error('wrote src/game/lateTuning.js');
}
